name: "library-managment-system"
services:
  db:
    image: postgres:17.6-alpine3.22
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    environment:
            - POSTGRES_HOST=db
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data: